### PR TITLE
Upgrade terraform library to 0.12.7

### PR DESCRIPTION
**Pull request by Nekroze**
This is a recommended pre-upgrade step before moving to the standalone [SDK](https://www.terraform.io/docs/extend/plugin-sdk.html) and should allow for terraform 12 and 11 support.

I have tested this myself deploying a machine to AWS with both terraform 0.12.x and 0.11.x successfully.

### CODE REVIEW

**Comment by Nekroze** [comment]
This gives tf12 support so I am not immediately going to try switch to the new SDK although there exists tooling to try do that for you:

https://github.com/hashicorp/tf-sdk-migrator

I will proceed to use this and probably do a PR for some other improvements in the near future before I revisit the SDK.

**Comment by andrewchambers** [comment]
Thank you so much, my use of this tool is not currently high, but I am interested in keeping it working well.

**Comment by Nekroze** [comment]
No problems at all, I am also thinking about creating some nix files to put in this repo so let me know what you think before I go ahead. Something to build the provider correctly, probably a `default.nix`, something to make getting `nixos-rebuild` on a non NixOS machine (atm I use a bit of nix to construct it out of nixpkgs in my project's `shell.nix` as most people around me use mac), and potentially a module and possibly (nixops) network like resource that has the same interface as NixOps as I use the module level options `nodes` and `resources` heaps to do scalable clustering without runtime service discovery.

The first two are pretty easy, the last one not so much and I am not entirely certain its a good idea. I will look first at trying to remove my usage of the nixops specific options and such first.

**Comment by andrewchambers** [comment]
Working on mac is something I would like, however I have never used a mac myself. I'm not sure what the module would look like so can't promise I would merge it, however if its something useful to you I can certainly take a look if you are planning on making it anyway.

**Pull request merged**
